version: "3"

services:

  app:
    container_name: backend_ms
    build: .
    ports:
      - "3333:3333"
    command: npm start
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.1.15
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=ms
      - DB_PORT=5433