version: "3"

services:

  ms-db:
    image: postgres:13
    ports: 
      - 5433:5432
    environment: 
      - POSTGRES_DB=ms
      - POSTGRES_PASSWORD=password
    volumes:
      - ms_postgresql:/var/lib/postgresql
      - ms_postgresql_data:/var/lib/postgresql/datas

volumes:
  ms_postgresql:
  ms_postgresql_data: