version: "3"

services:
    ms-db:
        image: postgres:13
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=ms
            - POSTGRES_PASSWORD=password
        volumes:
            - ms_postgresql:/var/lib/postgresql
            - ms_postgresql_data:/var/lib/postgresql/datas

    redis:
        image: redis
        command: redis-server
        ports:
            - "6379:6379"

volumes:
    ms_postgresql:
    ms_postgresql_data:
